spring.application.name=backend
app.jwt.secret=Q4W56GPqSmtryytcNlx9yDZhS8FI4bRlJrAAkwEDWjT
app.jwt.expiration-ms=86400000

# ==========================================
# DATABASE ? PostgreSQL (Docker + pgvector)
# ==========================================
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/grabpic_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:grabpic_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:grabpic_pass}
spring.datasource.driver-class-name=org.postgresql.Driver

# ==========================================
# JPA / HIBERNATE
# ==========================================
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# ==========================================
# GMAIL SMTP
# ==========================================
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=grabpicbackend@gmail.com
spring.mail.password=bencjwteidjwrmee
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# ==========================================
# OTP CONFIG
# ==========================================
app.otp.expiry-minutes=10
app.otp.max-attempts=3

# ==========================================
# PYTHON FACE SERVICE
# ==========================================
python.face.service.url=http://localhost:8001/embed
face.service.url=http://localhost:8001/embed

# ==========================================
# FILE UPLOAD CONFIG
# ==========================================
app.upload.dir=uploads
